version: 2.1

jobs:
  check_quality:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test

workflows:
  build_and_deploy:
    jobs:
      - check_quality
